### ISSUE TITLE
Response item does not use variables for timeout

### ISSUE THREAD

**Issue by MichlF** [open-cogsci/opensesame-extension-osweb#21]
I cannot use a variable to define the timeout of a response item. It will not a throw an error but revert to `infinite` when running the experiment in the browser.

For example:
Defining `long_timing = 1000;` in an inline_javascript and attempting to use it as timeout variable in a response item like so `[long_timing]` will result in a response item waiting until a response is given when running the experiment in the browser. No error is thrown.
By hardcoding the timeout with an integer in the response item directly, this problem is fixed.

I am using Open Sesame 3.3.3, Win10 and the Opensesame installation via Anaconda distribution.

**Comment by OmarEscamez** [comment]
Hello! I have been trying these days to solve this issue as well and I have found a different way that also seems to work. 

The problem:

The idea is that when you have in the same sequence 1) the inline with the variable (and its value) and 2) the keyboard with the timeout defined using that variable, it does not behave the way it should.

The way I have solved it:

In the same sequence that I have described above, instead of place a keyboard directly at the same level, I introduce a loop with a new sequence. In this new sequence I only introduce the keyboard. 

Note: When the variable you use for the keyboard has a value less or equal to 0, it does not work. If this is the case, you can set the 'Run if' of the loop (with the keyboard) when the value of the variable is higher than 0.

I hope it could help!
